// <auto-generated />
// Manual accessor class for ClaudeBar.Resources.Strings.*.resx files.
//
// This file is hand-written (rather than emitted by PublicResXFileCodeGenerator)
// so that the project builds via `dotnet build` on the command line without
// requiring the ResX code generator. The .resx files are still picked up as
// satellite assemblies via the <EmbeddedResource> entries in ClaudeBar.csproj.
//
// Keys here are PascalCase versions of the snake_case keys in
// /i18n/strings.yaml — the regenerate-translations.py script applies the
// same transformation when writing the .resx <data name="..."> attributes,
// so the two stay in sync as long as new YAML keys are added here too.
//
// English fallbacks are baked in so that, even if a satellite resource is
// missing at runtime (or the .resx files have not been regenerated yet),
// the UI still shows readable text.

using System.Globalization;
using System.Reflection;
using System.Resources;

namespace ClaudeBar.Resources;

public static class Strings
{
    private static readonly ResourceManager _rm = new(
        "ClaudeBar.Resources.Strings",
        typeof(Strings).Assembly);

    private static string Get(string key, string fallback)
    {
        try
        {
            return _rm.GetString(key, CultureInfo.CurrentUICulture) ?? fallback;
        }
        catch (MissingManifestResourceException)
        {
            return fallback;
        }
    }

    // -- Brand --------------------------------------------------------------
    public static string BrandName => Get(nameof(BrandName), "ClaudeBar");

    // -- Tray / panel menu items -------------------------------------------
    public static string MenuRefreshNow => Get(nameof(MenuRefreshNow), "Refresh now");
    public static string MenuOpenUsagePage => Get(nameof(MenuOpenUsagePage), "Open claude.ai/settings/usage");
    public static string MenuSettings => Get(nameof(MenuSettings), "Settings…");
    public static string MenuQuit => Get(nameof(MenuQuit), "Quit ClaudeBar");
    public static string MenuRefresh => Get(nameof(MenuRefresh), "Refresh");

    // -- Usage stat labels --------------------------------------------------
    public static string StatSession => Get(nameof(StatSession), "Current session");
    public static string StatSessionDash => Get(nameof(StatSessionDash), "Current session: —");
    public static string StatSessionWithPct => Get(nameof(StatSessionWithPct), "Current session: %d%%");
    public static string StatWeekly => Get(nameof(StatWeekly), "Weekly (all models)");
    public static string StatWeeklyDash => Get(nameof(StatWeeklyDash), "Weekly (all models): —");
    public static string StatWeeklyWithPct => Get(nameof(StatWeeklyWithPct), "Weekly (all models): %d%%");
    public static string StatResets => Get(nameof(StatResets), "Resets %s");

    // -- Time-relative formatting (used inside StatResets) ------------------
    public static string TimeNow => Get(nameof(TimeNow), "now");
    public static string TimeDash => Get(nameof(TimeDash), "—");
    public static string TimeInMinutes => Get(nameof(TimeInMinutes), "in %d min");
    public static string TimeInHours => Get(nameof(TimeInHours), "in %dh");
    public static string TimeInHoursMinutes => Get(nameof(TimeInHoursMinutes), "in %dh %dm");
    public static string TimeInDays => Get(nameof(TimeInDays), "in %dd");
    public static string TimeInDaysHours => Get(nameof(TimeInDaysHours), "in %dd %dh");

    // -- Status messages ----------------------------------------------------
    public static string StatusOffline => Get(nameof(StatusOffline), "Offline — last value may be stale");
    public static string StatusRateLimited => Get(nameof(StatusRateLimited), "Rate limited by Claude API");
    public static string StatusUnauthenticated => Get(nameof(StatusUnauthenticated), "Not signed in — open Settings to add a token");

    // -- Authentication UI --------------------------------------------------
    public static string AuthSignIn => Get(nameof(AuthSignIn), "Sign in with Claude");
    public static string AuthSignOut => Get(nameof(AuthSignOut), "Sign out");
    public static string AuthSignedInToken => Get(nameof(AuthSignedInToken), "Signed in (token ends '…%s')");
    public static string AuthNotSignedIn => Get(nameof(AuthNotSignedIn), "Not signed in");
    public static string AuthChecking => Get(nameof(AuthChecking), "Checking…");
    public static string AuthWaitingBrowser => Get(nameof(AuthWaitingBrowser), "Waiting for browser sign-in…");
    public static string AuthKeyringError => Get(nameof(AuthKeyringError), "Keyring error — see logs");
    public static string AuthSignInFailed => Get(nameof(AuthSignInFailed), "Sign-in failed");
    public static string AuthCouldNotStart => Get(nameof(AuthCouldNotStart), "Could not start sign-in");
    public static string AuthCopyLink => Get(nameof(AuthCopyLink), "Copy link");
    public static string AuthLinkCopiedNotify => Get(nameof(AuthLinkCopiedNotify), "Sign-in link copied to clipboard");

    // -- Preferences — page titles -----------------------------------------
    public static string PrefsAccount => Get(nameof(PrefsAccount), "Account");
    public static string PrefsDisplay => Get(nameof(PrefsDisplay), "Display");
    public static string PrefsAdvanced => Get(nameof(PrefsAdvanced), "Advanced");
    public static string PrefsGeneral => Get(nameof(PrefsGeneral), "General");
    public static string PrefsAuthentication => Get(nameof(PrefsAuthentication), "Authentication");
    public static string PrefsStatus => Get(nameof(PrefsStatus), "Status");
    public static string PrefsTopBar => Get(nameof(PrefsTopBar), "Top bar");
    public static string PrefsTrayIcon => Get(nameof(PrefsTrayIcon), "Tray icon");
    public static string PrefsColorThresholds => Get(nameof(PrefsColorThresholds), "Color thresholds");
    public static string PrefsRefreshSection => Get(nameof(PrefsRefreshSection), "Refresh");
    public static string PrefsLabels => Get(nameof(PrefsLabels), "Labels:");
    public static string PrefsAccountSubtitle => Get(nameof(PrefsAccountSubtitle),
        "Sign in with your Claude account to fetch Max plan usage. Tokens are stored in GNOME Keyring via libsecret.");
    public static string PrefsShowPercentages => Get(nameof(PrefsShowPercentages), "Show numeric percentages next to bars");
    public static string PrefsShowPercentagesSubtitle => Get(nameof(PrefsShowPercentagesSubtitle),
        "Small session and weekly percentages, stacked beside the bars.");
    public static string PrefsShowPercentagesBeside => Get(nameof(PrefsShowPercentagesBeside), "Show numeric percentages beside the bars");
    public static string PrefsColorThresholdsDesc => Get(nameof(PrefsColorThresholdsDesc), "When bars switch from green to orange to red.");
    public static string PrefsOrangeAtPct => Get(nameof(PrefsOrangeAtPct), "Orange at (%)");
    public static string PrefsRedAtPct => Get(nameof(PrefsRedAtPct), "Red at (%)");
    public static string PrefsOrangeAtShort => Get(nameof(PrefsOrangeAtShort), "Orange at (%):");
    public static string PrefsRedAtShort => Get(nameof(PrefsRedAtShort), "Red at (%):");
    public static string PrefsPollIntervalSeconds => Get(nameof(PrefsPollIntervalSeconds), "Poll interval (seconds)");
    public static string PrefsPollIntervalShort => Get(nameof(PrefsPollIntervalShort), "Poll interval (s):");
    public static string PrefsHelperPath => Get(nameof(PrefsHelperPath), "Helper binary:");

    // -- Floating desktop meter --------------------------------------------
    public static string MeterSection => Get(nameof(MeterSection), "Floating desktop meter");
    public static string MeterEnable => Get(nameof(MeterEnable), "Show always-on-top meter on the desktop");
    public static string MeterDesc => Get(nameof(MeterDesc),
        "Small transparent widget rendering full-size bars. Draggable into any corner; right-click to lock or hide.");
    public static string MeterShowPercentages => Get(nameof(MeterShowPercentages), "Show numeric percentages on the floating meter");
    public static string MeterShowPercentagesSubtitle => Get(nameof(MeterShowPercentagesSubtitle),
        "Adds session and weekly percentages next to the bars on the floating desktop meter (must be enabled below). The tray tooltip always shows percentages.");
    public static string MeterOpacity => Get(nameof(MeterOpacity), "Opacity:");
    public static string MeterWidthPx => Get(nameof(MeterWidthPx), "Width (px):");
    public static string MeterWidthHint => Get(nameof(MeterWidthHint), "(120–320)");
    public static string MeterLock => Get(nameof(MeterLock), "Lock position");
    public static string MeterUnlock => Get(nameof(MeterUnlock), "Unlock");
    public static string MeterHide => Get(nameof(MeterHide), "Hide meter");

    // -- Action buttons -----------------------------------------------------
    public static string ActionOk => Get(nameof(ActionOk), "OK");
    public static string ActionCancel => Get(nameof(ActionCancel), "Cancel");
    public static string ActionClose => Get(nameof(ActionClose), "Close");
    public static string ActionOpen => Get(nameof(ActionOpen), "Open");

    // -- Sign-in dialog -----------------------------------------------------
    public static string SigninDialogHeading => Get(nameof(SigninDialogHeading), "Sign in with Claude");
    public static string SigninDialogBody => Get(nameof(SigninDialogBody),
        "Your browser should have opened to claude.ai. Complete sign-in there, then return here. This dialog will close automatically.");

    // -- Window / tooltip text ---------------------------------------------
    public static string WindowPreferencesTitle => Get(nameof(WindowPreferencesTitle), "ClaudeBar");
    public static string TooltipDefault => Get(nameof(TooltipDefault), "ClaudeBar");
    public static string TooltipLines => Get(nameof(TooltipLines), "ClaudeBar\nSession: %d%%\nWeekly: %d%%");

    // -- Installer (also surfaced via WiX .wxl) ----------------------------
    public static string InstallerWelcome => Get(nameof(InstallerWelcome), "Welcome to the ClaudeBar Setup");
    public static string InstallerRuntimeStep => Get(nameof(InstallerRuntimeStep), ".NET 8 Desktop Runtime (x64)");
    public static string InstallerAppStep => Get(nameof(InstallerAppStep), "ClaudeBar");
}
